package org.biomart.common.general.utils;

public enum HackEnum {
	NO_HACK, DATASET_NOT_IDENTICALS_1, SAME_DATABASE, FULLY_DESCRIPTIVE_DATABASE_NAMES, FULLY_DESCRIPTIVE_SCRIPT_NAMES, 
	HIDE_FULL_RANGES, ON_LOCAL, MIDDLED, SUB_MIDDLED, DECREASING_OVERLAP;
}
