package org.biomart.test.linkIndicesTest.program;

public enum Mode {
	LINK_INDEX_CREATION,
	FULL_INTERACTIVE,
	FULL_NON_INTERACTIVE,
	INTERACTIVE,
	NON_INTERACTIVE,
	INTERACTIVE_WITH_LINK_INDEX_ONLY,
	INTERACTIVE_WITHOUT_LINK_INDEX_ONLY,
	NON_INTERACTIVE_WITH_LINK_INDEX_ONLY,
	NON_INTERACTIVE_WITHOUT_LINK_INDEX_ONLY,
LINK_INDEX_CREATION_TMP,USE_INDEX_TMP
}
